title: Max/MSP Externals 
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "View on GitHub":
    - "//github.com/max-externals/site"
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
compress_html:
  ignore:
    envs: all